
"""
Dataclasses and enums for evidence/alerts generated by all detection modules.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import List, Optional


class Direction(Enum):
    SRC = "SRC"
    DST = "DST"
    ANY = "ANY"


class IoCType(Enum):
    IP = "ip"
    DOMAIN = "domain"
    URL = "url"
    MD5 = "md5"
    SHA256 = "sha256"
    JA3 = "ja3"
    JA3S = "ja3s"
    IP_RANGE = "ip_range"
    ASN = "asn"
    COUNTRY = "country"
    HOSTNAME = "hostname"
    USER_AGENT = "user_agent"
    FILE_TYPE = "file_type"


class EvidenceType(Enum):
    """Every detection module should add its own EvidenceType member(s)."""
    ARP_SCAN = auto()
    DNS_SCAN = auto()
    ICMP_SCAN = auto()
    NOT_NEIGHBOR_ARP_REQUEST = auto()
    # --- OT / ICS ---
    OT_MODBUS_CONNECTION_FLOOD = auto()
    OT_MODBUS_WRITE_COILS = auto()
    OT_MODBUS_ILLEGAL_FUNCTION = auto()
    OT_S7COMM_JOB_FLOOD = auto()
    OT_S7COMM_PLC_STOP = auto()
    OT_S7COMM_UNAUTHORIZED_READ = auto()
    OT_S7COMM_UNAUTHORIZED_WRITE = auto()
    OT_DNP3_FLOOD = auto()
    OT_DNP3_UNAUTHORIZED_FUNCTION = auto()
    OT_PROFINET_DCP_FLOOD = auto()
    OT_CIP_MESSAGE_FLOOD = auto()
    OT_NTP_TIME_SYNC_ATTACK = auto()
    OT_PTP_SPOOFING = auto()
    OT_PLC_MODE_SWITCH = auto()
    OT_WATCHDOG_MANIPULATION = auto()
    OT_VALVE_CYCLING = auto()
    OT_MOTOR_CYCLING = auto()
    OT_UNAUTHORIZED_MODBUS_ACCESS = auto()
    OT_PROTOCOL_ANOMALY = auto()
    # --- General ---
    COMMAND_LINE_OVERFLOW = auto()
    COMMAND_AND_CONTROL_CHANNEL = auto()
    CRYPTO_MINING = auto()
    RANSOMWARE = auto()
    # --- sandbox, spam, etc. ---
    SANDBOX_DNS = auto()
    SPAM_EMAIL = auto()
    # Add more as modules require...


class ThreatLevel(Enum):
    """Unified threat-level scale."""
    INFO = 0
    LOW = 0.2
    MEDIUM = 0.5
    HIGH = 0.8
    CRITICAL = 1


class Proto(Enum):
    TCP = "TCP"
    UDP = "UDP"
    ICMP = "ICMP"
    ARP = "ARP"
    DHCP = "DHCP"
    DNS = "DNS"


@dataclass
class ProfileID:
    ip: str = ""

    def __str__(self):
        return f"profile_{self.ip}"


@dataclass
class TimeWindow:
    number: int = 0

    def __str__(self):
        return f"timewindow{self.number}"


@dataclass
class Attacker:
    direction: Direction
    ioc_type: IoCType
    value: str
    profile: Optional[ProfileID] = None


@dataclass
class Victim:
    direction: Direction
    ioc_type: IoCType
    value: str
    profile: Optional[ProfileID] = None


@dataclass
class Evidence:
    """
    Single piece of evidence produced by a detection module.
    The evidence handler collects these and converts them to alerts.
    """
    evidence_type: EvidenceType
    description: str
    attacker: Attacker
    threat_level: ThreatLevel
    profile: ProfileID
    timewindow: TimeWindow
    uid: List[str] = field(default_factory=list)
    timestamp: str = ""
    confidence: float = 0.5
    # Fields used by the evidence handler / alert pipeline
    victim: Optional[Victim] = None
    proto: Optional[Proto] = None
    dst_port: Optional[int] = None
    src_port: Optional[int] = None

    def __post_init__(self):
        """
        Accept ThreatLevel name string if needed.
        """
        if isinstance(self.threat_level, str):
            self.threat_level = ThreatLevel[self.threat_level.upper()]
        if isinstance(self.evidence_type, str):
            self.evidence_type = EvidenceType[self.evidence_type]
        if isinstance(self.proto, str):
            self.proto = Proto[self.proto.upper()]


def dict_to_evidence(data: dict) -> Evidence:
    """Convert a dict back into an Evidence object."""
    attacker_data = data.get("attacker", {})
    attacker = Attacker(
        direction=Direction[attacker_data.get("direction", "SRC")],
        ioc_type=IoCType[attacker_data.get("ioc_type", "IP")],
        value=attacker_data.get("value", ""),
        profile=ProfileID(ip=attacker_data.get("profile", "")),
    )

    victim_data = data.get("victim")
    victim = None
    if victim_data:
        victim = Victim(
            direction=Direction[victim_data.get("direction", "DST")],
            ioc_type=IoCType[victim_data.get("ioc_type", "IP")],
            value=victim_data.get("value", ""),
        )

    return Evidence(
        evidence_type=EvidenceType[data.get("evidence_type", "ARP_SCAN")],
        description=data.get("description", ""),
        attacker=attacker,
        threat_level=ThreatLevel[data.get("threat_level", "MEDIUM")],
        profile=ProfileID(ip=data.get("profile", "")),
        timewindow=TimeWindow(number=data.get("timewindow", 0)),
        uid=data.get("uid", []),
        timestamp=data.get("timestamp", ""),
        confidence=data.get("confidence", 0.5),
        victim=victim,
        proto=Proto[data.get("proto", "TCP")] if data.get("proto") else None,
        dst_port=data.get("dst_port"),
        src_port=data.get("src_port"),
    )
